variables: # TO be passed downstream
  DEPLOY_PROJECT: 'gcp-solutions/hcls/claims-modernization/pa-ref-impl/DRLS-GCP'
  DOCKER_FILE: 'Dockerfile.dev'

include:
- project: 'gcp-solutions/hcls/claims-modernization/gitlab-ci'
  file: '/.gitlab/ci/.build.gitlab-ci.yml'
- project: 'gcp-solutions/hcls/claims-modernization/gitlab-ci'
  file: '/.gitlab/ci/.deploy-trigger.gitlab-ci.yml'

stages:
- build
- vars #Dynamically generate file with parameters
- deploy

